# Homebrew formula for dotdipper.
# Generated by scripts/gen-formula.sh — do not edit by hand.
#
#   brew install psyysp/dotdipper/dotdipper

class Dotdipper < Formula
  desc "A safe, deterministic, and feature-rich dotfiles manager built in Rust"
  homepage "https://github.com/psyysp/dotdipper"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.8.1/dotdipper-aarch64-apple-darwin.tar.gz"
      sha256 "8f05b6d261bdfdd0556203dc2337104c3e580c8141b8ebde74b1f399b9c2f2bc"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.8.1/dotdipper-x86_64-apple-darwin.tar.gz"
      sha256 "c0cbe0b094ea6cc174999dda698298fe0e41ac4ddbac30a9021ec2488ebfc899"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.8.1/dotdipper-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "81ed5ec3d6202ba28a296f23ce6beea6bd716a1b8717d879b0e86fad18f78705"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.8.1/dotdipper-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "64efc16c8ecd5b66b2c09767ecb80bed564d372b6e57749da8f072ac37e208a9"
    end
  end

  depends_on "age"

  def install
    bin.install "dotdipper"
  end

  def caveats
    <<~EOS
      Dotdipper has been installed.

      To get started:
        dotdipper init

      For help:
        dotdipper --help
    EOS
  end

  test do
    assert_match "dotdipper", shell_output("#{bin}/dotdipper --version")
  end
end
