# Homebrew formula for dotdipper.
# Generated by scripts/gen-formula.sh — do not edit by hand.
#
#   brew install psyysp/dotdipper/dotdipper

class Dotdipper < Formula
  desc "A safe, deterministic, and feature-rich dotfiles manager built in Rust"
  homepage "https://github.com/psyysp/dotdipper"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.9.0/dotdipper-aarch64-apple-darwin.tar.gz"
      sha256 "68a47d0b4ca083c96047721d676fe7b5559b6972bf266134aaf024f642a5327e"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.9.0/dotdipper-x86_64-apple-darwin.tar.gz"
      sha256 "c538b938de628d7ef95b82c161db3b8c5552265f76a04853bc608f2314ede282"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.9.0/dotdipper-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "7bcf0adb9801114fef0b517d15ed758f484653b0f1668c4bd03e510fbf4c92d6"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.9.0/dotdipper-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8949d5027109ec14920ed48f16f62d4075d73f8af063993b90e622778a80e40f"
    end
  end

  depends_on "age"

  def install
    bin.install "dotdipper"
  end

  def caveats
    <<~EOS
      Dotdipper has been installed.

      To get started:
        dotdipper init

      For help:
        dotdipper --help
    EOS
  end

  test do
    assert_match "dotdipper", shell_output("#{bin}/dotdipper --version")
  end
end
