# Homebrew formula for dotdipper.
# Generated by scripts/gen-formula.sh — do not edit by hand.
#
#   brew install psyysp/dotdipper/dotdipper

class Dotdipper < Formula
  desc "A safe, deterministic, and feature-rich dotfiles manager built in Rust"
  homepage "https://github.com/psyysp/dotdipper"
  version "0.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.10.1/dotdipper-aarch64-apple-darwin.tar.gz"
      sha256 "8fd4440424ab652318241ee7f320360314ea71b212a8bf6858854016f922a285"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.10.1/dotdipper-x86_64-apple-darwin.tar.gz"
      sha256 "1d13aabf05304291ce4f8e420decb9b86f788afecfa8ae2e5acf94e8c58f5114"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.10.1/dotdipper-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "7e9d693c738c9287371b15500bd204060dccfe8f5d1aff6bcab517966b3f6cb4"
    end
    on_intel do
      url "https://github.com/psyysp/dotdipper/releases/download/v0.10.1/dotdipper-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4a74e85b8fc231cfac40e9898cf2b2ea5da44cf90202e15282a03c38c4244bb3"
    end
  end

  depends_on "age"

  def install
    bin.install "dotdipper"
  end

  def caveats
    <<~EOS
      Dotdipper has been installed.

      To get started:
        dotdipper init

      For help:
        dotdipper --help
    EOS
  end

  test do
    assert_match "dotdipper", shell_output("#{bin}/dotdipper --version")
  end
end
